version: "3"

services:
  postgres-db:
    image: "postgres"
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "postgrespw123"
      POSTGRES_DB: "LISTA_TAREFAS"
    ports:
     - "15432:5432"
    volumes:
     - "~/PostgreSQL/data:/var/lib/postgresql/data"
    networks:
     - lista-tarefas-network

  postgres-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rayonnunes"
      PGADMIN_DEFAULT_PASSWORD: "testepg123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - lista-tarefas-network

networks:
  lista-tarefas-network:
    driver: bridge